### ISSUE TITLE
Number of nioEventLoopGroup threads keeps on increasing if connection is not succesful

### ISSUE THREAD

**Issue by KeshavSirohi** [bitrich-info/xchange-stream#278]
Faced this issue when GDAX kept on trying for re-connection. Older nio threads were not getting shutdown. Thread dump showed more than 100 nioEventLoopGroup thread in Runnable state.
Below are the websocket logs:
2019-01-31 01:00:40,131  INFO nioEventLoopGroup-138-1 WebSocket Client connected!
2019-01-31 01:00:40,131  INFO nioEventLoopGroup-137-1 WebSocket Client connected!
2019-01-31 01:00:40,131  WARN nioEventLoopGroup-137-1 Resubscribing channels
2019-01-31 01:00:40,131  WARN nioEventLoopGroup-138-1 Resubscribing channels
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-135-1 WebSocket Client disconnected!
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-135-1 Reopening websocket because it was closed by the host
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-138-1 WebSocket Client disconnected!
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-138-1 Reopening websocket because it was closed by the host
2019-01-31 01:01:20,545  INFO globalEventExecutor-1-162 Connecting to wss://ws-feed.gdax.com:-1
2019-01-31 01:01:20,547  INFO globalEventExecutor-1-162 Registering GDAXWebSocketClientHandler
2019-01-31 01:01:20,548  INFO globalEventExecutor-1-162 Connecting to wss://ws-feed.gdax.com:-1
2019-01-31 01:01:20,550  INFO globalEventExecutor-1-162 Registering GDAXWebSocketClientHandler
2019-01-31 01:01:21,292  INFO nioEventLoopGroup-139-1 WebSocket Client connected!
2019-01-31 01:01:21,292  WARN nioEventLoopGroup-139-1 Resubscribing channels
2019-01-31 01:01:21,297  INFO nioEventLoopGroup-140-1 WebSocket Client connected!
2019-01-31 01:01:21,297  WARN nioEventLoopGroup-140-1 Resubscribing channels
2019-01-31 01:01:40,083  INFO nioEventLoopGroup-137-1 WebSocket Client disconnected!
2019-01-31 01:01:40,083  INFO nioEventLoopGroup-137-1 Reopening websocket because it was closed by the host
2019-01-31 01:01:40,084  INFO nioEventLoopGroup-140-1 WebSocket Client disconnected!

**Comment by badgerwithagun** [comment]
Possibly fixed by the shutdown added in #211? Been meaning to pick that one up.

**Comment by badgerwithagun** [comment]
Fixing this now.

**Comment by badgerwithagun** [comment]
@KeshavSirohi, which version was this on? I've just seen the gdax address in your logs, which suggests that it's quite old code. There are have been many fixes in this area recently.

**Comment by badgerwithagun** [comment]
#282 includes some potential catches for this issue, but I've not been able to replicate it.

**Comment by vinczeim** [comment]
Seems like something very similar still happened in our servers. See log cut and inline comments attached. We use version 4.3.15.

[xchange-stream_reconnect_issue.txt](https://github.com/bitrich-info/xchange-stream/files/3112738/xchange-stream_reconnect_issue.txt)
